### ISSUE TITLE
for RabbitMQ 3.4.1

### ISSUE THREAD

**Issue by memorycraft** [videlalvaro/rabbitmq-recent-history-exchange#12]
Hi, 

This Plugin is looks very nice. Please provide me binary for RabbitMQ 3.4.1.

Thanks
memorycraft

**Comment by videlalvaro** [comment]
Take a look here: http://www.rabbitmq.com/community-plugins/v3.4.x/ and this page as well: http://www.rabbitmq.com/community-plugins.html
