### ISSUE TITLE
Routing key is stripped

### ISSUE THREAD

**Issue by carlhoerberg** [videlalvaro/rabbitmq-recent-history-exchange#13]
Publishing to a remote x-recent-history exchange removes the routing key of messages :(

**Comment by carlhoerberg** [comment]
Actually, the routing_key is there for new messages delivered while the queue is bound, but all old messages that are put into the queue on bind don't have a routing_key.

**Comment by carlhoerberg** [comment]
Maybe bump the version number (1.2.1?) and release a new version to https://www.rabbitmq.com/community-plugins.html ? I can do it, is it just to post the .ez file to the mailing list?

**Comment by videlalvaro** [comment]
No, it doesn't work like that, we have a build system for community plugins. I'll ask @dumbbell

**Comment by videlalvaro** [comment]
A new version of the plugin should we up on our community plugins page

**Comment by dumbbell** [comment]
@carlhoerberg, to answer your question, to publish new or updated plugins to the community page, we run the `build-community-plugins.py` script in `rabbitmq-public-umbrella/release-build`. Once done, the script `deploy-community-plugins.py` uploads the artifacts to www.rabbitmq.com. Finally, one has to re-deploy the website so the `community-plugins.html` page is updated (the website is static).

Not very straightforward or community-oriented :-)
