### ISSUE TITLE
Only new queues receive exchange history

### ISSUE THREAD

**Issue by ethagnawl** [videlalvaro/rabbitmq-recent-history-exchange#16]
This might 1) be by design or 2) because I'm doing something wrong (probably the case...), but I'm only seeing the message history delivered to new queues.

Here's my code (I'm using the Bunny Ruby client):

```
@conn = Bunny.new(ENV['CLOUDAMQP_URL'])
@conn.start
@ch = @conn.create_channel
@x = @ch.exchange("video-exchange",
                  type: "x-recent-history",
                  arguments: { 'x-recent-history-length' => 1 })

# will only receive history payload once
queue_name = "queue-1"
@ch.queue(queue_name).bind(@x).subscribe do |_, _, payload|
  puts "!!!!!!!!! '#{payload}' on #{queue_name}"
end

# will always receive history payload
queue_name = "queue-#{SecureRandom.hex}"
@ch.queue(queue_name).bind(@x).subscribe do |_, _, payload|
  puts "!!!!!!!!! '#{payload}' on #{queue_name}"
end
  ```

**Comment by videlalvaro** [comment]
As per the README:

>Every time a queue is bound to the exchange it delivers that last 20 messages to them.

So only during queue.bind a queue will receive messages from the history

**Comment by ethagnawl** [comment]
Thanks for the prompt response! However, I'm still not seeing the behavior as described, so any suggestions would be greatly appreciated. 

To expand on the above:

> So only during queue.bind a queue will receive messages from the history

Unless this is intended to be _only_ the first time a queue _ever_ binds (which doesn't seem to be the case), I'm not seeing this behavior. 

If my client goes down and then re-subscribes using the same queue name (e.g. "queue-1") once it comes back online, it does not receive the history. If it re-subscribes using a dynamic queue name (e.g. "queue-1-18"), it does receive the history.

**Comment by videlalvaro** [comment]
queue.bind is idempotent at protocol level, so if the binding is there, the
second time the command is kinda ignored.

**Comment by ethagnawl** [comment]
Good to know. Thanks! :+1:
